---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional :
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
implicit :
  - У интернет-магазина должна быть форма регистрации
  - Сервер интернет-магазина должен обеспечивать безопасное хранение информации клиентов
  - Форма регистрации и любые другие поля ввода информации должны обеспечивать защиту от атак типа XSS, SQL Injection
  - Обеспечить постоянную сессию с помощью соответствующих cookies 
  - Корректность отображения ошибки при некорректном запросе или отсутствии соединения с сетью
  - Должна быть возможность корректировки количества товара либо при его добавлении в корзину, либо непосредственно в корзине
  - Должно быть уведомление о том, что товар был успешно добавлен в корзину
  - При реализации мультиязычности, так же необходимо реализовывать её в описании товаров
